import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Main from '../components/mainPage/Main'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ===================00===================== */}
      {/* ===================00===================== */}
      {/* <Link href="/admin">admin</Link> */}
      <Main />
    </div>
  )
}